### ISSUE TITLE
How to get rid of empty black space at bottom.

### ISSUE THREAD

**Issue by TheGuyWhoo** [torcado194/scritch-player#3]
![Screenshot from 2022-04-05 18-18-58](https://user-images.githubusercontent.com/72744967/161800217-a74fa407-1ab0-4eda-849d-50db2718ba44.png)

Hey! I really like the player, but this is a small issue I've been running into. If I try to reduce the height here, I get scroll bars which are really unsightly imo. I would like to be able to size it such a way so there's as little empty space as possible.

**Comment by torcado194** [comment]
Thank you for pointing this out! This was due to a couple reasons, mainly that the main container has a bottom margin so that there's a bit of extra space at the bottom when scrolling the track list. 

I just pushed a fix for this, which removes space if no description is set.
Let me know if that works for you!

**Comment by TheGuyWhoo** [comment]
Hi, yes it works! Thank you very much. One other thing that would be nice is if I could turn off the list(the area where you select the song) if I'm using the player for a single song.

**Comment by torcado194** [comment]
Great! Happy to help :)
That's a nice suggestion, I may add an option to disable the track list in the future (in case someone wants to hide it even if they have multiple tracks). For now, you can add this to the custom CSS:
```css
#tracks {
    display: none;
}
```

**Comment by TheGuyWhoo** [comment]
Thanks!
